### ISSUE TITLE
Bug in Search & Conversation node.js API: cannot list datastore

### ISSUE THREAD

**Issue by edudesouza** [googleapis/google-cloud-node#4846] opened 2023-11-22 12:19 UTC
#### Environment details

  - which product (packages/*): 
  - OS: Google Cloud Functions
  - Node.js version: Node 18.15.0
  - npm version: 9.5.0
  - google-cloud-node version:  running cloud function local emulator

#### Steps to reproduce

Hi there, following this doc:

https://github.com/googleapis/google-cloud-node/blob/main/packages/google-cloud-discoveryengine/samples/generated/v1alpha/data_store_service.list_data_stores.js

I cannot list  DataStore, but the interesting part is ... the error log points to another project ID, error message, even if I left parent path blank.

ERROR: 7 PERMISSION_DENIED: Discovery Engine API has not been used in project 563584335869 before or it is disabled. Enable 
it by visiting https://console.developers.google.com/apis/api/discoveryengine.googleapis.com/overview?project=563584335869 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry. 

My Code:
![image](https://github.com/googleapis/google-cloud-node/assets/177087/25ed09e6-d8a9-4504-bb49-ca8cb2a450b7)

ERROR Print metadata:
![image](https://github.com/googleapis/google-cloud-node/assets/177087/c1e9e4db-6dc2-4c2a-b349-eaa7a500aa32)

**Comment by sofisl** [comment] 2023-11-27 21:05
Closing this as a duplicate of https://github.com/googleapis/google-cloud-node/issues/4845

**Closed by sofisl** 2023-11-27 21:05 UTC
