### ISSUE TITLE
PULL_REQUEST_TEMPLATE.md should reference CONTRIBUTING

### ISSUE THREAD

**Issue by jsoref** [googleapis/google-cloud-node#2992] opened 2020-03-06 16:12 UTC
https://github.com/googleapis/nodejs-dlp/blob/master/.github/PULL_REQUEST_TEMPLATE.md should link to something which talks about conventionalcommits.org -- if only https://github.com/googleapis/nodejs-dlp/blob/master/CONTRIBUTING.md

**Comment by fhinkel** [comment] 2020-12-07 11:50
I think it's fine to keep the template short. It's just an additional reminder and not a duplicate of https://github.com/googleapis/nodejs-dlp/blob/master/CONTRIBUTING.md

**Closed by fhinkel** 2020-12-07 11:50 UTC
Labels: type: docs
